name: Update GitLab Activity Graph

on:
  schedule:
    - cron: "0 15 * * *" # 12:00 PM BRT
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    continue-on-error: true
    permissions:
      contents: write

    steps:
      - name: Cancel if runner offline
        uses: peter-evans/cancel-offline-runner@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install python-gitlab svgwrite

      - name: Generate Graph
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
        run: python .github/scripts/gitlab_heatmap.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gitlab-graph.svg
          git commit -m "Update GitLab contribution graph" || echo "No changes"
          git push
