name: Update GitLab Activity Graph

on:
  schedule:
    - cron: "0 15 * * *" # 12PM BRT
  workflow_dispatch:

jobs:
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner_online: ${{ steps.status.outputs.runner_online }}

    steps:
      - name: Check runner online status
        id: status
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_GITLAB_HEATMAP_EXPORTER_PAT_TOKEN }}
        run: |
          IS_ONLINE=$(
            gh api repos/${{ github.repository }}/actions/runners \
              --jq 'any(.runners[]; .status == "online")'
          )

          echo "runner_online=$IS_ONLINE" >> $GITHUB_OUTPUT

  build:
    needs: check-runner
    if: ${{ needs.check-runner.outputs.runner_online == 'true' }}
    runs-on: self-hosted
    continue-on-error: true
    permissions:
      contents: write

    steps:
      - name: Debug runner_online
        run: echo "runner_online=${{ needs.check-runner.outputs.runner_online }}"

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install python-gitlab svgwrite

      - name: Generate Graph
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
        run: python .github/scripts/gitlab_heatmap.py

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add gitlab-graph.svg
          git commit -m "Update GitLab contribution graph" || echo "No changes"
          git push
